#cloud-config

---
write_files:
- path: /home/core/registry.service
  owner: core:core
  permissions: 420
  content: |
    [Unit]
    Description=pvt docker registry
    Requires=docker.service
    After=docker.service

    [Service]
    User=core
    TimeoutStartSec=0
    KillMode=none
    #EnvironmentFile=/tsad-proj/tsad-sys/env #make a global fs
    ExecStartPre=-/usr/bin/docker kill registry
    ExecStartPre=-/usr/bin/docker rm registry
    ExecStartPre=/usr/bin/docker load --input \
    /tsad-proj/tsad-bigfiles/images/docker-registry/registry.tar
    ExecStart=/usr/bin/docker run \
    --name registry \
    -i \
    -e SETTINGS_FLAVOR=dev \
    -e STORAGE_PATH=/registry \
    -p 5000:5000 \
    registry
    ExecStop=/usr/bin/docker stop registry
- path: /home/core/btsyncb.service
  owner: core:core
  permissions: 420
  content: |
    [Unit]
    Description=btsync for  bootstrapping cluster with files
    Requires=docker.service
    After=docker.service

    [Service]
    User=core
    TimeoutStartSec=0
    KillMode=none
    ExecStartPre=-sudo mkdir /home/core/bootstrap
    ExecStartPre=-/usr/bin/docker kill btsyncb
    ExecStartPre=-/usr/bin/docker rm btsyncb
    ExecStartPre=/usr/bin/docker pull mkaag/btsync
    ExecStart=/usr/bin/docker run \
    --name btsyncb \
    -i \
    -e "SECRET=BFACKCCBAFUZZ3YHL2ENSZXPRT6CKGNXH" \
    -p 55555:55555 \
    -v /home/core/bootstrap:/data \
    mkaag/btsync
    ExecStop=/usr/bin/docker stop registry

    [X-Fleet]
    Global=true
coreos:
  etcd:
    discovery: https://discovery.etcd.io/70ab4bfc0015cb80e46b8f847fb374dc
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  fleet:
    public-ip: $public_ipv4
    metadata: loc=local
  units:
  - name: etcd.service
    command: start
  - name: fleet.service
    command: start
  - name: docker.service
    drop-ins:
    - name: 50-insecure-registry.conf
      content: |
        [Service]
        Environment=
        Environment=DOCKER_OPTS='--insecure-registry="172.17.1.0/24"'
    command: start
  - name: docker-tcp.socket
    command: start
    enable: true
    content: |
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      ListenStream=2375
      Service=docker.service
      BindIPv6Only=both

      [Install]
      WantedBy=sockets.target
  - name: auto-start-registry.service
    command: start
    content: |
      [Unit]
      Description=Autostarts registry-service
      Requires=docker.service
      After=docker.service

      [Service]
      WorkingDirectory=/home/core/
      ExecStart=/usr/bin/fleetctl start registry.service
      Type=oneshot
  - name: auto-start-btsyncb.service
    command: start
    content: |
      [Unit]
      Description=Autostarts btsyncb
      Requires=docker.service
      After=docker.service

      [Service]
      WorkingDirectory=/home/core/
      ExecStart=/usr/bin/fleetctl start btsyncb.service
      Type=oneshot
  - name: 10-weave.network
    runtime: false
    content: |
      [Match]
      Type=bridge
      Name=weave*

      [Network]
  - name: install-weave.service
    command: start
    enable: true
    content: |
      [Unit]
      After=network-online.target
      After=docker.service
      Description=Install Weave
      Documentation=http://zettio.github.io/weave/
      Requires=network-online.target
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/bin/mkdir -p /opt/bin/
      ExecStartPre=/usr/bin/curl \
      --silent \
      --location \
      https://github.com/weaveworks/weave/releases/download/latest_release/weave \
      --output /opt/bin/weave
      ExecStartPre=/usr/bin/chmod +x /opt/bin/weave
      ExecStartPre=/usr/bin/docker pull zettio/weave:latest
      ExecStartPre=/usr/bin/docker pull zettio/weavetools:latest
      ExecStartPre=/usr/bin/docker pull zettio/weavedns:latest
      ExecStart=/bin/echo Weave Installed
