# -*- mode: ruby -*-
# vi: set ft=ruby :

#WINDOWZ issuez
#run vagrant cmds from cygwin
#adds /c/cygdrive to /c/path/to/wherever
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
#run emacs from git shell!

Vagrant.configure(2) do |config|

  config.vm.network "private_network", ip: "192.168.12.34"
  config.vm.synced_folder "../../tsad", "/tsad" , type: "rsync"
  #config.vm.synced_folder "../../data", "/data" #maybe

  config.vm.define "files" do |f|
    f.vm.provider "docker" do |d|
      d.build_dir = "../docker/files"
      d.remains_running= false
    end
  end

  

end
