---
# tasks file for ansiblevagrant


- name: make a vagrant box that ansible knows about
  vagrant:
    command: "{{command}}"
    box_name: "{{box_name}}"
    vm_name:  "{{vm_name}}"
#    box_path: "{{bxpth.stdout}}"
    log: "{{log}}"
    config_code: "{{config_code}}"
    vagrant_root: "{{playbook_dir}}"
    count: "{{count}}"
    forward_ports: #[] doesn't work!
    share_folder: '{{share_folder}}'
    share_mount: '{{share_mount}}'
  register: vagrant

#have to have this task if i want the next play to work.
#b/c ansible doesn't have the inventory yet

- name: add host info to inventory
  add_host:
    groupname=vagrant_hosts
    hostname='{{item.hostname}}'
    ansible_ssh_port='{{item.port}}'
    ansible_ssh_host='{{item.public_ip}}'
    ansible_ssh_user='{{item.username}}'
    ansible_ssh_private_key_file='{{item.key}}'
    pvt_ip='{{item.internal_ip}}'
  with_items: '{{vagrant.instances}}'
  when: "'{{command}}'=='up'"
  
#ref. library/vagrant
# 'name' : vm_name,
# 'vagrant_name' : vagrant_name,
# 'hostname' : vagrant_name.replace('_','-'),
# 'id': cnf['Host'],
# 'public_ip': cnf['HostName'],
# 'internal_ip': inst['internal_ip'],
# 'public_dns_name': cnf['HostName'],
# 'port' : cnf['Port'],
# 'username' : cnf['User'],
# 'key' : cnf['IdentityFile'],
# 'status' : self.vg.status(vagrant_name)   