
# Deploy cloudconfig and run coreos-cloudinit


- name: Install cloudconfig #just here in case of templating
  template: src="{{cconfig}}.tmp" dest=/home/core/user_data
  register: installcc
  tags: cc

- name: Run coreos-cloudinit
  raw: sudo coreos-cloudinit --from-file=/home/core/user_data
  when: installcc.changed #ansible is awesome
  tags: cc
