---

#cloud-config

write_files:
- path: /home/core/sys.env
- path: /etc/profile.d/sys_env.sh
  #todo: make a compute-local config that uses the insecure reg w/ mirr
  #since it's best to get imgs locally
  #and a compute-remote config that doesn't use mirr
- path: /etc/systemd/system/docker.service.d/50-insecure-registry-mirr.conf
- path: /home/core/waitforfile.sh




coreos:
  
  update:
    
    reboot-strategy: 'off'
    
  fleet:
    
    metadata: role=compute #, loc=local
    public-ip: '{{public_ip}}' #todo : put fleet on weave

  etcd2:
    
    discovery: ${DISCOVERY_URL}
    advertise-client-urls: http://{{public_ip}}:2379
    initial-advertise-peer-urls: http://{{public_ip}}:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://{{public_ip}}:2380  

    
  units:
#  - name: fleet.service
#todo: have remote machines see my etcd through some nat rules
#  - name: etcd2.service 
  - name: docker.service
  - name: 10-weave.network
  - name: install-weave.service
  - name: weave.service
    command: stop
  - name: weavedns.service
    command: stop
  - name: weaveproxy.service
    command: stop
  - name: projectfiles.service
    command: stop
  - name: keepnfsalive.service
    #todo: why do i have to do this?!?! iptables issue??
    command: stop
    content: |
      [Unit]
      Description=hack for keeing nfs connection
      After=   projectfiles.service
      Requires=projectfiles.service
      [Service]
      ExecStartPre=/usr/bin/mkdir -p ${PROJECT_DIR}
      ExecStartPre=/home/core/waitforfile.sh ${PROJECT_DIR}/root.dir
      ExecStart=/usr/bin/sh -c 'cd ${PROJECT_DIR};  \
      while true; do /usr/bin/ls; sleep 10; done'
    
