---

#cloud-config

hostname: $CHOSTNAME


coreos:
  fleet:
    metadata: loc=local , role=init
    public-ip: $public_ipv4
  units:
  - name: etcd2.service
  - name: fleet.service
  - name: projectfiles.service
  - name: varlibdocker.service
    command: start
    content: |
      [Unit]
      After=projectfiles.service
      Requires=projectfiles.service
      Before=docker.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=-/tsad-proj/tsad-sys/docker/create_varlibdocker.sh
      ExecStart=/usr/bin/mountpoint -q /home/core/vld
  - name: var-lib-docker.mount
    command: start
    content: |
      [Unit]
      Description=Mount to /var/lib/docker
      Requires=varlibdocker.service
      After=varlibdocker.service
      Before=docker.service
      [Mount]
      #mounting /dev/varlibdocker does not work!!!!
      What=/home/core/vld
      Where=/var/lib/docker
      Options=bind
  - name: docker.service
  - name: docker-tcp.socket
  - name: 10-weave.network
  - name: loadregimg.service
  - name: install-weave.service
  - name: weave.service
  - name: weavedns.service
  - name: weaveproxy.service
  - name: stuffregistry.service
#    content: |
#      [Service]
#      ExecStart=/usr/bin/echo stub
  - name: registry.service
  - name: fileshare.service
    
write_files:
- path: /etc/modules-load.d/loop.conf
  content: |
    loop
- path: /etc/modprobe.d/eightloop.conf
  content: |
    options loop max_loop=64
- path: /home/core/sys.env
- path: /etc/profile.d/sys_env.sh
- path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
- path: /home/core/waitforfile.sh

