---
#cloud-config

hostname: $CHOSTNAME

coreos:
  
  update:
    reboot-strategy: 'off'
  fleet:
    metadata: loc=local , role=init
    public-ip: "{{public_ip}}"
  etcd2:
    discovery: ${DISCOVERY_URL}
    advertise-client-urls: http://{{public_ip}}:2379
    initial-advertise-peer-urls: http://{{public_ip}}:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://{{public_ip}}:2380  

  units:
#  - name: docker-tcp.socket
#  - name: fleet.service
#  - name: etcd2.service
  - name: projectfiles.service
  - name: varlibdocker.service
    command: start
    content: |
      [Unit]
      After=projectfiles.service
      Requires=projectfiles.service
      Before=docker.service
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=-${PROJECT_DIR}/setup/varlibdocker.sh
      ExecStart=/usr/bin/mountpoint -q /home/core/vld
  - name: var-lib-docker.mount
    command: start
    content: |
      [Unit]
      Description=Mount to /var/lib/docker
      Requires=varlibdocker.service
      After=varlibdocker.service
      Before=docker.service
      [Mount]
      #mounting /dev/varlibdocker does not work!!!!
      What=/home/core/vld
      Where=/var/lib/docker
      Options=bind
  - name: docker.service
  - name: 10-weave.network
  - name: loadregimg.service
  - name: install-weave.service
  - name: weave.service #todo: chk if fails if varlibdocker is from scratch
  - name: weavedns.service
  - name: weaveproxy.service
  - name: registry.service
  - name: stuffregistry.service #todo tst if htis long proc makes a prblm
#    content: |
#      [Service]
#      ExecStart=/usr/bin/echo skip this
  - name: fileshare.service
    content: |
      [Unit]
      Description=expose fileshare to network
      Requires=weaveproxy.service
      After=   weaveproxy.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes

      ExecStart=/opt/bin/weave expose \
      ${WEAVE_EXPOSE_IP}/${WEAVE_MANL_BIT}
      
      ExecStartPre=/home/core/fwd.sh tcp \
      ${WEAVE_EXPOSE_IP} 111 $NFS_SERVER 111
      ExecStartPre=/home/core/fwd.sh udp \
      ${WEAVE_EXPOSE_IP} 111 $NFS_SERVER 111
      ExecStartPre=/home/core/fwd.sh tcp \
      ${WEAVE_EXPOSE_IP} 2049 $NFS_SERVER 2049
      ExecStartPre=/home/core/fwd.sh udp \
      ${WEAVE_EXPOSE_IP} 2049 $NFS_SERVER 2049
      ExecStartPre=/home/core/fwd.sh tcp \
      ${WEAVE_EXPOSE_IP} $NFS_PORT $NFS_SERVER $NFS_PORT
      ExecStartPre=/home/core/fwd.sh udp \
      ${WEAVE_EXPOSE_IP} $NFS_PORT $NFS_SERVER $NFS_PORT

      ExecStart=/usr/bin/echo file share exposed
      
          
    
write_files:
- path: /etc/modules-load.d/loop.conf
  content: |
    loop
- path: /etc/modprobe.d/eightloop.conf
  content: |
    options loop max_loop=64
- path: /home/core/sys.env
- path: /etc/profile.d/sys_env.sh
- path: /etc/systemd/system/docker.service.d/50-insecure-registry-mirr.conf
- path: /home/core/waitforfile.sh
- path: /home/core/fwd.sh

