---

#makes the the coreosbox that provides for initial svcs


- hosts:
    - localhost
  gather_facts: false
  vars:
    vagrant_machine: "{{v}}" #specify -e v=init from cmd line
    
  roles:
    - role: "{{vagrant_machine}}"
      tags: cc
    - role: cloudconfigwriter
      write_cconfig_pth: "{{playbook_dir}}/roles/coreos-bootstrap/templates/{{vagrant_machine}}"
      cconfig: "{{vagrant_machine}}"
      tags: cc
    
        
  tasks:

    - name: add host info to inventory
      add_host:
        groupname=vagrant_hosts
        hostname='{{item.vagrant_name}}'
        ansible_ssh_port='{{item.port}}'
        ansible_ssh_host='{{item.public_ip}}'
        ansible_ssh_user='{{item.username}}'
        ansible_ssh_private_key_file='{{item.key}}'
      with_items: '{{vagrant.instances}}'
      tags: cc #
       
    - set_fact: vagrant_machine={{vagrant_machine}}
      tags: cc

   

- hosts:
    - vagrant_hosts
  gather_facts: false
  
  roles:
    - role: coreos-bootstrap
      cconfig: "{{hostvars['localhost']['vagrant_machine']}}"

- hosts: localhost
  gather_facts: true
  roles:
    - role: ssh_config
      ssh_config_hosts: "{{groups.vagrant_hosts}}"
    


      