---

#vagrantfile and box file paths are relative to remote

- stat: path={{out_boxfile}} get_checksum=false
  register: boxfilestats
- name: does box file exist?
  set_fact:
    boxfile_exists: "{{boxfilestats.stat.exists}}"
- name: should continue this? 
  set_fact:
    shouldrun: "{{overwrite}} == true or ({{overwrite}} == false and {{boxfile_exists}} == false)"


- name: install virtualbox  on linux
  package: name=virtualbox state=latest
  when: ansible_env.OS.lower().find('windows') == -1
- name: install virtualbox on windows
  win_chocolatey:
    name: virtualbox
    upgrade: true
  when: false #ansible_env.OS.lower().find('windows') != -1
    
- name: install vagrant on linux
  package: name=vagrant state=latest
  when: ansible_env.OS.lower().find('windows') == -1
- name: install vagrant on windows
  win_chocolatey:
    name: vagrant
    upgrade: true
  when: false #ansible_env.OS.lower().find('windows') != -1

#todo should resstart the windows machine
#install cygwin? ansible_system=CYGWINblahblah
#then get the lcoation of the bash interpreter..so that the following
#would work


#no 'v2' block for now
#- block:

- name: temporary box file name
  shell: echo $(dirname {{in_vagrantfile}})/some.box
  register: tempbox
  when: shouldrun
- name: remove temporary box # todo: best if error handler
  file: path={{tempbox.stdout}} state=absent
  when: shouldrun
      
- name: make vagrant box on the remote in the vagrantfile dir
  #the script changes to the vagrantfile dir.
  #so the out box is in the same dir as vagrantfile
  script: make_box.sh {{in_vagrantfile}} some.box
  when: shouldrun
  
- name: move box file
  shell: cd $(dirname {{in_vagrantfile}}) && mv -f some.box {{out_boxfile}}
  when: shouldrun

#  always: #not working!!
    # - name: temporary box file name
    #   shell: echo $(dirname in_vagrantfile)/some.box
    #   register: tempbox
    # - name: remove box # todo: best if error handler
    #   file: path={{tempbox.stdout}} state=absent

      

