# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  
  config.vm.box = "coreos-alpha"
  
  config.vm.network "private_network", ip: "192.168.179.13"
                         #1st 3 digits sort of hard coded

  config.vm.synced_folder ENV['local_projectdir'] , ENV['remote_projectdir'], type: "nfs"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "create swapfile",
                      type: "shell" do |swapfile|
    swapfile.inline="fallocate -l 4G /swapfile && \
                     chmod 600       /swapfile && \
                     mkswap          /swapfile && \
                     swapon          /swapfile"
  end
  
  config.vm.provision "docker registry img creation",
                      type: "shell" do |registry|
    registry.inline= "cd $1/setup && ./registry_img.sh"
    registry.args= "#{ENV['remote_projectdir']}"
  end

  config.vm.provision "btrfs f/s creation for /var/lib/docker",
                      type: "shell" do |varlibdocker|
    varlibdocker.inline= "cd $1/setup && ./varlibdocker.sh"
    varlibdocker.args= "#{ENV['remote_projectdir']}"
    varlibdocker.privileged= true #it's the default anyways
  end

  config.vm.provision "stuff docker registry",
                      type: "shell" do |stuffregistry|
    stuffregistry.inline= "cd $1/setup && ./stuffregistry.sh"
    stuffregistry.args= "#{ENV['remote_projectdir']}"
    stuffregistry.privileged= true #it's the default anyways
  end  


    
end

