#!/bin/sh

source ../common.src
export remote_projectdir=`$ENVCMD PROJECT_DIR remote`
#                          sigh the shared folder guest pth must be abs
export local_projectdir=`$ENVCMD NFS_SHARE_VAGRANT`
export registry_host=`$ENVCMD REGISTRY_WHOST`

vagrant "$@"

