#!/bin/sh

source ../common.src
export remote_projectdir=`$ENVCMD PROJECT_DIR remote`
#                          sigh the shared folder guest pth must be abs
export local_projectdir="../"
#export local_projectdir=`$ENVCMD PROJECT_DIR local`
#wont work on windows but no big deal

vagrant "$@"

