---
# defaults file for ansiblevagrant

log: "true"
box_name: ubuntu/vivid64
command: up
vagrant_root: "{{playbook_dir}}"

share_project: "false"

cpus: 1
memory: 1024

config_code: |
  config.vm.provider "virtualbox" do |vb|
      vb.memory = {{memory}}
      vb.cpus = {{cpus}}
  end

  
count: 1
vm_name: ansiblevagrant


share_folder: "" #for no shared folders

#  config.vm.synced_folder "{{lookup('pipe',xenv+'NFS_SHARE')}}", \
share_mount:  "{{lookup('pipe',xenv+'PROJECT_DIR remote')}}"
