---



#http://docs.ansible.com/ansible/ec2_module.html

- set_fact:
    _coreos_json: "{{ lookup('pipe',_coreos_curl)  }}" #no from_json !
- set_fact:
    latest_image: "{{ _coreos_json[ec2_vars.defaults.region][ec2_vars.defaults.virt]  }}"

- name: provision ec2 instances
  ec2:
    aws_access_key: '{{aws_access_key}}'
    aws_secret_key: '{{aws_secret_access_key}}'
    key_name: personalcomputecloud
    image: '{{image}}'
    #state: '{{state}}' params exact_count and state are mutually exclu??
##https://groups.google.com/forum/#!searchin/ansible-project/exact_count$20stopped$20instances/ansible-project/hYoM9Pv1Aa4/qVXm9S2k5jQJ
    group: personalcomputecloud
    region: '{{region}}'
    instance_type: "{{instance_type}}"
    instance_tags:
      Name: '{{name}}'
    exact_count: '{{count}}'
    count_tag:
      Name: '{{name}}'
    volumes: #by default you get a paltry 8GB of spc so...
    #..the following resizes
      - device_name: /dev/xvda #the root device
        #todo: how to be more programmatic about which is the root vol?
        #it's given after the fact
        volume_size: 40
        device_type: gp2
        delete_on_termination: true
    wait: yes #have to to get the info...
  register: ec2 #...or nothing will show up in ec2


- name: wait for instance to show up in inventory
  shell: '{{inventory_dir}}/ec2.sh --list --refresh-cache'
  register: ec2i
  until: ec2i.stdout.find(item.public_dns_name) != -1
  #todo: apply |from_json jinja filter
  with_items: ec2.instances #cool so if count=0 (wait=y) this..
  #..task will skip
  retries: 30
  delay: 10
  changed_when: false
  